{% set name = "google-cloud-bigquery-storage" %}
{% set version = "0.3.0" %}
{% set sha256 = "3a41fef405383fcf562540341bb55ffad88de506972ab494777c9005d45f9ec1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - enum34  # [ py < 34 ]
    - google-api-core >=1.6.0,<2.0.0dev
    - grpcio >=1.8.2


test:
  imports:
    - google
    - google.cloud
    - google.cloud.bigquery_storage_v1beta1
    - google.cloud.bigquery_storage_v1beta1.gapic
    - google.cloud.bigquery_storage_v1beta1.gapic.transports
    - google.cloud.bigquery_storage_v1beta1.proto

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "BigQuery Storage API API client library"
  doc_url: https://googleapis.github.io/google-cloud-python/latest/bigquery_storage/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/master/bigquery_storage

extra:
  recipe-maintainers:
    - pshiko
    - tswast
