travis:
  secure:
    BINSTAR_TOKEN: miTrhwQCMpkBrF7b5PzB7BX1F1EwD4NC+looQQbosi4qr0snjJ7cyb4ynuQqYjFWlKtlwKRhYFEqzQY50INECi9SYVzC39BHHw3tznRF8X9RAiEeT59G4/V7JWAReFaHRHMJMRYA9muiJMrHwbtE25NUcTX4T6D0lfpLHd/4LZpHsWQSuveH15Wp95VVrbXw0V2eQngc0ZqFjEaQUDiEWxWPoddY8YQFOAW4p+jsb7Jq7ibPnyYoVMGpLihH4Tm9U48uY3KmIRCDToZKeZzEU0D4PBvMMmEZQSy7MWDP9lq1XQC9i3C4PPPJELNMjVWiyz9sTUCc569a4X6z91pVHevSFhMP1B3H2r71gic5SIuuXIg5Zfb7fzNNExPdrz0k3+XT79AmIBnGZUDoqDHtOeK6kgpFyZNMHpqE3+3/bbxKebe1Y24OpYsvlpROHgAeMc7MJVzZsjZdra5QFqMUrYxcNhXQXGUFKlXrsqYZWbFvC49HZs+8ejQxnoe58oiNdzu8AOl8rvQVrI9gUEehWi3oZHNJ57r4JpPcto4WQHhKuw6mbMLT6K/L+YLxpE2aUpfsq+E6G8JqmtzadozxUDZbPdlEax4HxdRe+te4Qm3RjVpiKtW3rj6qDaiEB+DWP5HFG6WJjF+73M/ShmHXcKwUb/rKt2nbYPgP72ItHtg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
